import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import { ToastContainer } from "react-toastify";
import { Providers } from ".";
import Header from "@/components/header";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "You App",
  description: "Generated by create next app",
}

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  const headersList = headers();
  const pathname = headersList.get("x-pathname");

  return (
    <html lang="en">
      <body
        className={`min-h-screen bg-${pathname?.split("/")[1] == "auth" ? "gradial" : "main"} py-[37px] max-w-[420px] ${inter.className}`}
      >
        <Providers>
          <Header />
          {children}
        </Providers>
        <ToastContainer />
      </body>
    </html>
  );
}
